### ISSUE TITLE
Track last written datapoint for an address

### ISSUE THREAD

**Issue by fractalcat** [anchor/chevalier#23] opened 2014-11-23 10:23 UTC
Currently systems such as Borel are making many unnecessary requests to the vault for addresses which haven't had any new data for significant periods of time. If a 'last point written' timestamp were included in the source document, such applications could filter out the addresses which aren't relevant to the time period being queried.

**Comment by olorin** [comment] 2015-02-20 04:56
Duplicate of #10.

**Closed by olorin** 2015-02-20 04:56 UTC
Labels: enhancement
